set(_CATKIN_CURRENT_PACKAGE "mvs_ros_driver")
set(mvs_ros_driver_VERSION "0.0.0")
set(mvs_ros_driver_MAINTAINER "xuankuzcr <zhengcr@todo.todo>")
set(mvs_ros_driver_PACKAGE_FORMAT "2")
set(mvs_ros_driver_BUILD_DEPENDS "cv_bridge" "image_transport" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(mvs_ros_driver_BUILD_EXPORT_DEPENDS "cv_bridge" "image_transport" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(mvs_ros_driver_BUILDTOOL_DEPENDS "catkin")
set(mvs_ros_driver_BUILDTOOL_EXPORT_DEPENDS )
set(mvs_ros_driver_EXEC_DEPENDS "cv_bridge" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(mvs_ros_driver_RUN_DEPENDS "cv_bridge" "roscpp" "rospy" "sensor_msgs" "std_msgs" "image_transport")
set(mvs_ros_driver_TEST_DEPENDS )
set(mvs_ros_driver_DOC_DEPENDS )
set(mvs_ros_driver_URL_WEBSITE "")
set(mvs_ros_driver_URL_BUGTRACKER "")
set(mvs_ros_driver_URL_REPOSITORY "")
set(mvs_ros_driver_DEPRECATED "")